home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('storykeren', include('tambahan.urls'))
]

tambahan/urls.py
from django.urls import path

from . import views

app_name = 'tambahan'

urlpatterns = [
    path('', views.index, name='stori'),
    path('gallery/', views.gallery, name='stori2')
]

home/models.py
from django.db import models

# Create your models here.

tambahan/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
   return render(request, 'home/index.html')

tambahan/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
   return render(request, 'home/stori.html')

def gallery(request):
   return render(request, 'home/stori2.html')

home/templates/base.html
{% load static %}
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel = "stylesheet" href = "{% static 'stori.css' %}">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg navbar-light bg-white naav">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <a class="nav-link nav-text" href="{% url 'home:index' %}">story 1</a>
            <a class="nav-link nav-text" href="{% url 'tambahan:stori' %}#aboutme">about</a>
            <a class="nav-link nav-text" href="{% url 'tambahan:stori' %}#sekolah">education</a>
            <a class="nav-link nav-text" href="{% url 'tambahan:stori' %}#pengalaman">experience</a>
            <a class="nav-link nav-text" href="{% url 'tambahan:stori2' %}">gallery</a>
          </div>
        </div>
      </nav>
</head>

<body>
  {% block content %}
  {% endblock %}
    
</body>

<footer>
    <div id="sosmed">
        <div class="container sosmed">
        <div class="row justify-content-center sekolah" >
          <div class="col-sosmed">
            <a href="https://twitter.com/ammar_syarif"  target="_blank"><img class="foto-sosmed" src="{% static 'twitter.png' %}"></a>
            <a href="https://www.linkedin.com/in/ammar-faridzki-syarif-460a951a0/"  target="_blank"><img class="foto-sosmed" src="{% static 'linkedin.png' %}"></a>
            <a href="https://instagram.com/syarifammarr" target="_blank"><img class="foto-sosmed" src="{% static 'instagram.png' %}"></a>
            <a href="https://api.whatsapp.com/send?phone=87885350602&text=Halo%20Ammar!" target="_blank"><img class="foto-sosmed" src="{% static 'whatsapp.png' %}"></a>
          </div>
         
        </div>
      </div>
      </div>
</footer>

home/templates/home/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'home/style.css' %}">


    <table class="navigator">
        <tr>
            <th><label  class="judulNav" id="tentangGua">tentang gua</label></th>
            <th><label  class="judulNav" id="kenalLebihDekat">kenal lebih dekat</label></th>
        </tr>
    </table>
    <div class="row">
        <div class="column">
            <img src="{% static 'home/1.png' %}" id="ammar">
        </div>
        <div class="column">
            <h1>nama gua <label class="nama">Ammar</label></h1>
            <p id ="tentang">Halo semua! Kenalin nama gua <label class="nama">Ammar Faridzki Syarif</label> (NPM 1906353712), dan lo bisa panggil gua Ammar.
               Gua adalah salah satu bagian dari keluarga Maung, yaitu angkatan 2019-nya Fakultas Ilmu Komputer
               Universitas Indonesia. 
            </p>
            <p id ="deskripsi">Kalo lo udah kenal gua, pasti lo udah tau betapa tertariknya gua dengan olahraga.
               Gua hobi banget main futsal dan sepak bola! Bahkan selama kuliah, kayanya gua lebih sering ngabisin waktu 
               gua buat olahraga dibanding buat ngoding depan laptop HAHAHA. Selain olahraga, gua juga suka banget
               ngabisin waktu bareng temen-temen. Mungkin karena itulah, gua sendiri merasa bahwa gua adalah pribadi
               yang memiliki jiwa sosial yang tinggi. Oke! Karena lo udah kenal gua, gua pengen ngucapin selamat
               datang di website ini! Selamat men-<i>stalk</i> !
            </p>
        </div>
    </div>
    <div>
        <div class="juds">
        <label class ="judulNav">riwayat pendidikan</label></div>
        <table>
            <tr>
                <th> <img src="{% static 'home/1.png' %}" ></th>
                <th> <img src="{% static 'home/3.png' %}"></th>
                <th> <img src="{% static 'home/2.png' %}" id="fasilkom"></th>
            </tr>    
            <tr>
                <th><label class="namaSekolah">tk-sd-smp al-fath</label></th>
                <th><label class="namaSekolah">sman 82 jakarta</label>
                <th><label class="namaSekolah">fakultas ilmu komputer ui</label></th>
            </tr>
        </table>
    </div>
    <div class="futer">
    <div class="footer">
        <tr>
            <th><a href="https://www.linkedin.com/in/ammar-faridzki-syarif-460a951a0/"  target="_blank"><img src="{% static 'home\linkedin.png' %}" class="sosmed"></a></th>
            <th><a href="https://twitter.com/ammar_syarif"  target="_blank"><img src="{% static 'home\twitter.png' %}" class="sosmed"></a></th>
            <th><a href="https://instagram.com/syarifammarr" target="_blank"><img src="{% static 'home\instagram.png' %}" class="sosmed"></a></th>
            <th><a href="https://api.whatsapp.com/send?phone=87885350602&text=Halo%20Ammar!" target="_blank"><img src="{% static 'home\whatsapp.png' %}" class="sosmed"></a></th>
        </tr>   
    </div>
</div>
{% endblock %}

tambahan/templates/home/stori.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="jumbotron bekgron">
    <h1>welcome</h1>
  </div>

  <div id="aboutme">
    <div class="container">
      <div class="row">
        <div class="col-sm foto-gue">
          <img src = "{% static 'ammarasli.png' %}">
        </div>
        <div class="col-sm col-about-text">
          <span class = "about-me">about me <br></span>
          <span id = "about-me-text">halo semua! kenalin nama gue Ammar Faridzki Syarif, dan lo bisa panggil gue Ammar. gue adalah salah satu bagian dari keluarga Maung, yaitu angkatan 2019-nya Fakultas Ilmu Komputer Universitas Indonesia.
            gue suka banget olahraga, terutama futsal. karena itulah, gue milih beberapa kepanitiaan dan organisasi yang bergerak di bidang olahraga.
          </span>
        </div>
      </div>
    </div>
  </div>

  <div id="sekolah">
    <div class="container div-sekolah">
      <div class="container edu-bg">  
        <h1>educational background</h1>
      </div>
      <div class="row sekolah">
        <div class="col-sm">
          <img class="foto" src="{% static 'Group4.png' %}"> 
          <div class="nama-sekolah">smp alfath</div> 
        </div>
        <div class="col-sm">
          <img class="foto" src="{% static 'Group3.png' %}">
          <div class="nama-sekolah">sman 82</div> 
        </div>
        <div class="col-sm">
          <img class="foto" src="{% static 'Group2.png' %}">
          <div class="nama-sekolah">fasilkom ui</div> 
        </div>
      </div>
    </div>
  </div>

  <div id="pengalaman">
    <div class="container">
      <div class="container div-sekolah"> 
        <div class="container edu-bg">  
          <h1>fasilkom experiences</h1>
        </div>
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="row">
              <div class="col-sm bg-pengalaman">
                <img class="foto-exp" src="{% static 'Grouop10.png' %}" alt="Third slide">
              </div>
              <div class="col-sm col-about-text">
                <span class = "pengalaman"> depor fasilkom<br></span>
                <span class = "pengalaman-text">gue adalah salah satu staff dari departemen olahraga bem fasilkom ui atau yang biasa disebut depor. menurut gue, depor itu cocok banget sama gue, karena selain bisa nambah pengalaman, gue juga ngejalanin dengan perasaan senang.
              </div>
            </div>
          </div>
          
          <div class="carousel-item">
            <div class="row">
              <div class="col-sm bg-pengalaman" >
                <img class=" foto-exp" src="{% static 'Grouop12.png' %}" alt="Third slide">
              </div>
              <div class="col-sm col-about-text">
                <span class = "pengalaman" >compfest 12<br></span>
                <span class = "pengalaman-text">di compfest, gue jadi staff playground, yaitu salah satu divisi di event. di divisi ini, tugas gue adalah mengapproach perusahaan untuk menjadi exhibitor di playground compfest. menurut gue, compfest bener-bener mengasah skill komunikasi gue.
                </span>
              </div>
            </div>
          </div>

          <div class="carousel-item">
            <div class="row">
              <div class="col-sm bg-pengalaman">
                <img class=" foto-exp" src="{% static 'Grouop11.png' %}" alt="Third slide">
              </div>
              <div class="col-sm col-about-text">
                <span class = "pengalaman">perak fasilkom<br></span>
                <span class = "pengalaman-text">menurut gue, perak adalah salah satu wadah terbaik untuk melepas penat di fasilkom. maka dari itu, gue memutuskan untuk menjadi salah satu bagian dari acara ini. divisi gue adalah futsal runner, dengan pic super ganteng yaitu fajar anugerah.  
                </span>
              </div>
            </div>
          </div>
          
        </div>
        <a class="carousel-control-prev"  href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next"  href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock %}

tambahan/templates/home/stori2.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="jumbotron bekgron">
        <h1>gallery</h1>
    </div>
    <div class="container foto-gallery">
        <div class="row sekolah">
          <div class="col-sm">
            <img class="img-fluid foto-foto" src="{% static 'ammar139535.jpg' %}"> 
          </div>
          <div class="col-sm">
            <img class="img-fluid foto-foto" src="{% static 'S__46915601.jpg' %}">
          </div>
          
        </div>
        
    </div>
    <div class="container foto-gallery">
        <div class="row sekolah">
          <div class="col-sm">
            <img class="img-fluid foto-foto" src="{% static 'yey_200302_0012.jpg' %}"> 
          </div>
          <div class="col-sm">
            <img class="img-fluid foto-foto" src="{% static 'samlaikum olim_191108_0002.jpg' %}">
          </div>
          
        </div>
        
    </div>
    <div class="container foto-gallery">
        <div class="row sekolah">
          <div class="col-sm">
            <img class="img-fluid foto-foto" src="{% static 'ammar139533.jpg' %}"> 
          </div>
          <div class="col-sm">
            <img class="img-fluid foto-foto" src="{% static 'faridzki276702.jpg' %}">
          </div>
          
        </div>
        
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock %}